---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "f1nalboss.de"
subtitle: "Public services"
#logo: "logo.png"
icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a>'

# Will load custom CSS files. Especially useful for custom icon sets.
stylesheet:
  - "assets/custom.css"

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link-hover: "#ffdd57"

# Optional message
#message:
#  url: https://services.f1nalboss.de
#  style: "is-dark"
#  title: "Services Overview"
#  icon: "fa fa-grin"
#  content: "This is a list of all services run on my Docker Swarm Cluster."

message:
  url: https://uselessfacts.jsph.pl/random.json?language=de
  mapping:
    content: 'text'
  title: "Interesting Fact?"
  content: "Cannot display a nice fact at the moment, searching...."

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  #  - name: "Private"
  #    icon: "fas fa-file-alt"
  #    url: "#private"
  - name: "Zugang beantragen"
    icon: "fa fa-envelope"
    url: "https://www.paulscode.de/#contact"
    target: "_blank"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Application"
    icon: "fas fa-cloud"
    items:
      - name: "Website"
        logo: "icons/paulscode.jpg"
        subtitle: "personal company website"
        tag: "business"
        url: "https://www.knulst.de"
        target: "_blank"
      - name: "PaulsBlog"
        logo: "icons/bludit.png"
        subtitle: "self hosted bludit blog where i write down all my stuff"
        tag: "informative"
        url: "https://blog.f1nalboss.de"
        target: "_blank"
      - name: "KnulstMeet"
        logo: "icons/jitsi.png"
        subtitle: "personal jitsi installation used for video meetings"
        tag: "better than zoom"
        url: "https://meet.knulst.de"
        target: "_blank"
      - name: "NextCloud"
        url: "https://cloud.knulst.de"
        logo: "icons/nextcloud.svg"
        tag: "awesome"
        subtitle: "beste Cloud wo gibt"
        target: "_blank"
      - name: "PaulsBin"
        logo: "icons/privatebin.png"
        subtitle: "a complete free to use pastebin alternative. pastes are saved encypted without server access!"
        tag: "privacy first"
        url: "https://paste.f1nalboss.de"
        target: "_blank"
      - name: "Mealie"
        url: "https://mealie.knulst.de"
        logo: "icons/mealie.png"
        tag: "delicious"
        subtitle: "Mealie is a self hosted recipe manager and meal planner with a RestAPI backend and a reactive frontend application."
        target: "_blank"
      - name: "Gitlab"
        logo: "icons/gitlab.png"
        subtitle: "personal gitlab for all my private and customer related projects done by paulscode"
        tag: "free"
        url: "https://git.f1nalboss.de"
        target: "_blank"
  - name: "in progress"
    icon: "fas fa-tasks"
    items:
      - name: "Calendso"
        url: "https://github.com/calendso/calendso"
        logo: "icons/calendso.png"
        tag: "free"
        target: "_blank"
        subtitle: "The open-source Calendly alternative."
      - name: "InstaPy"
        tag: "free"
        subtitle: "Tooling that automates your social media interactions to “farm” Likes, Comments, and Followers on Instagram Implemented in Python using the Selenium module."
        logo: "https://camo.githubusercontent.com/48b5c67f0baa5b41fc98c96dad8de4771b0fc583d6b3dda417c7f8e01e801028/68747470733a2f2f692e696d6775722e636f6d2f734a7a665a734c2e6a7067"
        url: "https://github.com/timgrossmann/InstaPy"
        target: "_blank"
      - name: "Wetty"
        tag: "free"
        subtitle: "Terminal over HTTP and https."
        url: "https://github.com/butlerx/wetty"
        target: "_blank"
      - name: "Linx"
        tag: "free"
        subtitle: "Self-hosted file/media sharing website."
        url: "https://github.com/andreimarcu/linx-server"
        target: "_blank"
  - name: "tested but discarded"
    icon: "fas fa-undo"
    items:
      - name: "PaulsBoard"
        logo: "icons/youtrack.svg"
        subtitle: "over top. not feasible for small teams"
        tag: "useless"
        url: "#"
        target: "_blank"
      - name: "penpot"
        logo: "icons/penpot.png"
        subtitle: "imho useless. just use other tools"
        tag: "just bad"
        url: "#"
        target: "_blank"